export const cartDesigns = [
  {
    id: "classic-white",
    name: "Classic White",
    description: "Timeless elegance with a pristine white finish",
    image: "/white-mobile-bar-cart-with-wooden-top-beach-setup-.jpg",
    features: ["White painted base", "Natural wood counter", "Classic styling", "Versatile for any event"],
    price: 299,
    fullDescription:
      "Our Classic White mobile bar cart combines timeless elegance with practical functionality. The pristine white painted base pairs beautifully with the natural wood counter, creating a versatile aesthetic that complements any event theme. Perfect for weddings, corporate events, or backyard celebrations.",
    specifications: [
      'Dimensions: 36" W x 24" D x 42" H',
      "Natural oak wood counter top",
      "Durable outdoor-grade paint",
      "Heavy-duty wheels for easy mobility",
      "Includes built-in storage shelf",
    ],
    included: [
      "Mobile cart base",
      "Wood counter top",
      "Setup and delivery within 20 miles",
      "Basic styling consultation",
    ],
  },
  {
    id: "coastal-blue",
    name: "Coastal Blue",
    description: "Ocean-inspired with soft blue tones",
    image: "/light-blue-mobile-bar-cart-coastal-theme-beach-par.jpg",
    features: ["Sky blue base", "Whitewashed wood top", "Nautical accents", "Perfect for beach events"],
    price: 329,
    fullDescription:
      "Bring the coastal vibes to your event with our Coastal Blue cart. Featuring a soft sky blue base and whitewashed wood top, this cart captures the essence of oceanside living. Ideal for beach weddings, summer parties, and waterfront celebrations.",
    specifications: [
      'Dimensions: 36" W x 24" D x 42" H',
      "Whitewashed pine counter top",
      "Weather-resistant finish",
      "All-terrain wheels",
      "Marine-grade hardware",
    ],
    included: [
      "Mobile cart base",
      "Whitewashed wood top",
      "Nautical rope accents",
      "Setup and delivery",
      "Styling accessories",
    ],
  },
  {
    id: "boho-chic",
    name: "Boho Chic",
    description: "Rustic charm with natural textures",
    image: "/rustic-boho-mobile-bar-cart-macrame-decorations-na.jpg",
    features: ["Natural wood finish", "Macramé details", "Woven accents", "Bohemian aesthetic"],
    price: 349,
    fullDescription:
      "Embrace the free-spirited bohemian aesthetic with our Boho Chic cart. Featuring natural wood finishes, handcrafted macramé details, and woven accents, this cart brings warmth and character to any celebration. Perfect for outdoor festivals, garden parties, and boho weddings.",
    specifications: [
      'Dimensions: 36" W x 24" D x 42" H',
      "Reclaimed wood construction",
      "Handcrafted macramé decorations",
      "Smooth-rolling casters",
      "Natural fiber accents",
    ],
    included: [
      "Rustic mobile cart",
      "Macramé hanging decorations",
      "Woven basket accessories",
      "Setup and delivery",
      "Boho styling package",
    ],
  },
  {
    id: "tropical-paradise",
    name: "Tropical Paradise",
    description: "Vibrant colors and tropical vibes",
    image: "/tropical-themed-mobile-bar-cart-colorful-tiki-styl.jpg",
    features: ["Bamboo accents", "Tiki styling", "Tropical decorations", "Island party ready"],
    price: 369,
    fullDescription:
      "Transform your event into an island paradise with our Tropical Paradise cart. Complete with bamboo accents, tiki styling, and vibrant tropical decorations, this cart brings the spirit of the islands to any celebration. Perfect for luaus, tiki parties, and tropical-themed events.",
    specifications: [
      'Dimensions: 36" W x 24" D x 42" H',
      "Natural bamboo details",
      "Tiki bar styling",
      "Weather-resistant construction",
      "Island-inspired hardware",
    ],
    included: [
      "Tiki-styled mobile cart",
      "Bamboo accents",
      "Tropical decorations",
      "Tiki torches (battery-operated)",
      "Setup and delivery",
    ],
  },
  {
    id: "modern-noir",
    name: "Modern Noir",
    description: "Sophisticated black with gold accents",
    image: "/modern-black-mobile-bar-cart-gold-accents-luxury-e.jpg",
    features: ["Matte black base", "Gold hardware", "Contemporary design", "Upscale events"],
    price: 389,
    fullDescription:
      "Make a bold statement with our Modern Noir cart. The sophisticated matte black finish paired with luxurious gold hardware creates an upscale aesthetic perfect for elegant evening events, corporate galas, and modern weddings. Contemporary design meets timeless luxury.",
    specifications: [
      'Dimensions: 36" W x 24" D x 42" H',
      "Premium matte black finish",
      "Brass gold hardware",
      "High-quality wheels",
      "Sleek modern profile",
    ],
    included: [
      "Modern black mobile cart",
      "Gold accent details",
      "Premium styling",
      "White glove delivery",
      "Luxury event consultation",
    ],
  },
  {
    id: "vintage-romance",
    name: "Vintage Romance",
    description: "Soft pastels with romantic details",
    image: "/vintage-pink-mobile-bar-cart-floral-decorations-ro.jpg",
    features: ["Blush pink finish", "Distressed details", "Floral accents", "Perfect for weddings"],
    price: 359,
    fullDescription:
      "Create an enchanting atmosphere with our Vintage Romance cart. The soft blush pink finish with distressed vintage details and delicate floral accents brings romantic charm to weddings, bridal showers, and intimate celebrations. A perfect blend of nostalgia and elegance.",
    specifications: [
      'Dimensions: 36" W x 24" D x 42" H',
      "Distressed blush pink finish",
      "Vintage-style hardware",
      "Smooth-rolling wheels",
      "Shabby chic aesthetic",
    ],
    included: [
      "Vintage-styled mobile cart",
      "Floral decoration package",
      "Romantic styling accessories",
      "Setup and delivery",
      "Wedding coordination",
    ],
  },
]

export const equipmentItems = [
  {
    id: "beach-umbrella",
    name: "Beach Umbrella",
    description: "Large 7ft beach umbrella with tilt function",
    image: "/large-beige-beach-umbrella-with-fringe-trim-elegan.jpg",
    price: 45,
    colors: ["Cream", "White", "Blue", "Coral", "Striped"],
    category: "Shade",
    fullDescription:
      "Our premium beach umbrellas provide essential shade and style for your outdoor event. Featuring a generous 7-foot diameter, tilt function for optimal sun protection, and elegant fringe trim, these umbrellas combine functionality with aesthetic appeal.",
    specifications: [
      "7ft diameter canopy",
      "Tilt mechanism for sun tracking",
      "Sturdy aluminum pole",
      "Wind-resistant design",
      "UV protection fabric",
    ],
    included: ["Beach umbrella with fringe", "Weighted base", "Setup and installation"],
  },
  {
    id: "tiki-umbrella",
    name: "Tiki Umbrella",
    description: "Authentic thatched tiki umbrella for tropical vibes",
    image: "/thatched-tiki-umbrella-tropical-palm-straw-beach-p.jpg",
    price: 65,
    colors: ["Natural", "Palm"],
    category: "Shade",
    fullDescription:
      "Bring authentic island atmosphere to your event with our thatched tiki umbrellas. Made from natural palm materials, these umbrellas create an instant tropical paradise and provide excellent shade coverage for your bar cart or seating area.",
    specifications: [
      "8ft diameter coverage",
      "Natural palm thatch",
      "Bamboo pole construction",
      "Authentic tiki styling",
      "Weather-treated materials",
    ],
    included: ["Tiki umbrella", "Bamboo pole", "Ground stake", "Setup service"],
  },
  {
    id: "market-umbrella",
    name: "Market Umbrella",
    description: "9ft market umbrella with wood pole",
    image: "/elegant-market-umbrella-wooden-pole-outdoor-dining.jpg",
    price: 55,
    colors: ["White", "Navy", "Sage", "Terracotta"],
    category: "Shade",
    fullDescription:
      "Our elegant market umbrellas offer superior shade coverage with sophisticated style. The 9-foot diameter and classic wood pole design make these umbrellas perfect for upscale events, garden parties, and outdoor dining experiences.",
    specifications: [
      "9ft diameter canopy",
      "Hardwood pole",
      "Fade-resistant fabric",
      "Pulley lift system",
      "Premium construction",
    ],
    included: ["Market umbrella", "Weighted base", "Professional setup"],
  },
  {
    id: "fringe-decor",
    name: "Fringe Decorations",
    description: "Metallic fringe trim for cart customization",
    image: "/metallic-fringe-tassels-party-decoration-silver-go.jpg",
    price: 25,
    colors: ["Gold", "Silver", "Rose Gold", "Mixed"],
    category: "Decor",
    fullDescription:
      "Add shimmer and movement to your mobile bar cart with our premium metallic fringe decorations. These high-quality fringe trims transform your cart with eye-catching texture and sparkle, perfect for festive celebrations and photo opportunities.",
    specifications: [
      "10ft total length",
      "Metallic finish",
      "Easy attachment system",
      "Multiple color options",
      "Reusable design",
    ],
    included: ["Fringe decoration garland", "Attachment clips", "Installation assistance"],
  },
  {
    id: "led-lights",
    name: "LED String Lights",
    description: "Battery-powered LED lights for evening events",
    image: "/warm-led-string-lights-outdoor-party-ambiance-ligh.jpg",
    price: 35,
    colors: ["Warm White", "Cool White", "Multicolor"],
    category: "Lighting",
    fullDescription:
      "Create magical ambiance for evening events with our premium LED string lights. Battery-powered for flexible placement, these lights add warmth and sparkle to your mobile bar cart and surrounding area without the need for electrical outlets.",
    specifications: ["20ft length", "50 LED bulbs", "8 lighting modes", "Battery or USB powered", "Weather-resistant"],
    included: ["LED string lights", "Battery pack", "Timer function", "Installation service"],
  },
  {
    id: "cooler",
    name: "Premium Cooler",
    description: "Large capacity cooler with ice",
    image: "/stainless-steel-party-cooler-ice-bucket-beverages.jpg",
    price: 40,
    colors: ["Stainless", "White", "Black"],
    category: "Essentials",
    fullDescription:
      "Keep beverages perfectly chilled throughout your event with our premium large-capacity cooler. Featuring excellent insulation and stylish design, this cooler holds ice for hours and accommodates dozens of beverages for your guests.",
    specifications: [
      "50-quart capacity",
      "Heavy-duty insulation",
      "Stainless steel or powder-coated finish",
      "Drainage plug",
      "Built-in bottle opener",
    ],
    included: ["Premium cooler", "Initial ice fill", "Bottle opener", "Delivery and pickup"],
  },
  {
    id: "glassware-set",
    name: "Glassware Set",
    description: "Set of 50 premium plastic glasses",
    image: "/elegant-clear-plastic-glassware-cocktail-glasses-p.jpg",
    price: 30,
    colors: ["Clear", "Colored"],
    category: "Essentials",
    fullDescription:
      "Serve your beverages in style with our premium plastic glassware set. These high-quality glasses look like real glass but offer the safety and convenience of plastic, perfect for outdoor events, poolside parties, and beach celebrations.",
    specifications: [
      "50-piece set",
      "12oz capacity",
      "Shatterproof plastic",
      "Elegant design",
      "Disposable or reusable",
    ],
    included: ["50 premium plastic glasses", "Protective storage", "Backup glasses available"],
  },
  {
    id: "serving-tray",
    name: "Serving Trays",
    description: "Set of 3 decorative serving trays",
    image: "/wooden-and-metal-serving-trays-party-catering-eleg.jpg",
    price: 20,
    colors: ["Wood", "Gold", "Silver"],
    category: "Essentials",
    fullDescription:
      "Complete your bar cart setup with our elegant serving tray collection. This set of three decorative trays in varying sizes provides practical serving surfaces while enhancing the visual appeal of your mobile bar presentation.",
    specifications: [
      "3-piece set (Small, Medium, Large)",
      "Multiple finish options",
      "Raised edges",
      "Non-slip surface",
      "Easy to clean",
    ],
    included: ["3 serving trays", "Cleaning and sanitizing", "Delivery service"],
  },
  {
    id: "signage",
    name: "Custom Signage",
    description: "Personalized acrylic or wood signs",
    image: "/elegant-custom-wedding-signage-acrylic-wood-bar-me.jpg",
    price: 50,
    colors: ["Clear", "White", "Wood"],
    category: "Decor",
    fullDescription:
      "Personalize your event with custom signage designed specifically for your celebration. Choose from elegant acrylic or rustic wood options, perfect for displaying menus, welcome messages, or special announcements at your mobile bar cart.",
    specifications: [
      '12" x 18" size',
      "Professional printing",
      "Acrylic or wood substrate",
      "Custom text and design",
      "Includes stand",
    ],
    included: ["Custom designed sign", "Display stand", "Design consultation", "Proof approval process"],
  },
]

export const packages = [
  {
    id: "beach-bliss",
    name: "Beach Bliss Package",
    description: "Everything you need for a perfect beach celebration",
    image: "/white-mobile-bar-cart-with-wooden-top-beach-setup-.jpg",
    originalPrice: 489,
    packagePrice: 399,
    savings: 90,
    items: ["Classic White Cart", "Beach Umbrella (Cream)", "Cooler with Ice", "Glassware Set (50pc)"],
    popular: true,
    fullDescription:
      "The Beach Bliss Package is your complete solution for a stunning beach celebration. We've curated the perfect combination of our Classic White mobile bar cart with essential beach event accessories. This package includes everything you need to create an unforgettable oceanside experience for your guests.",
    specifications: [
      "Classic White mobile bar cart with natural wood top",
      "Large 7ft Beach Umbrella in Cream with fringe trim",
      "Premium 50-quart cooler with initial ice fill",
      "50-piece premium plastic glassware set",
      "Professional setup and delivery within 20 miles",
    ],
    idealFor: ["Beach Weddings", "Oceanside Parties", "Coastal Celebrations", "Summer Events"],
    rentalDetails: {
      minimumRental: "4 hours",
      deliveryIncluded: "Within 20 miles",
      setupTime: "30-45 minutes",
      pickupTime: "Next day pickup available",
    },
  },
  {
    id: "tropical-party",
    name: "Tropical Party Package",
    description: "Turn any event into an island paradise",
    image: "/tropical-themed-mobile-bar-cart-colorful-tiki-styl.jpg",
    originalPrice: 549,
    packagePrice: 449,
    savings: 100,
    items: ["Tropical Paradise Cart", "Tiki Umbrella", "LED String Lights", "Fringe Decorations (Gold)"],
    popular: true,
    fullDescription:
      "Transform your event into a tropical paradise with our most popular package. Featuring our vibrant Tropical Paradise cart, authentic tiki umbrella, sparkling LED lights, and glamorous gold fringe decorations, this package creates an immersive island experience your guests will love.",
    specifications: [
      "Tropical Paradise mobile cart with bamboo accents",
      "8ft authentic thatched Tiki Umbrella",
      "20ft LED String Lights (battery-powered, 8 modes)",
      "10ft Metallic Gold Fringe Decorations",
      "Complete setup and styling service",
    ],
    idealFor: ["Luaus", "Tiki Parties", "Birthday Celebrations", "Corporate Events"],
    rentalDetails: {
      minimumRental: "4 hours",
      deliveryIncluded: "Within 20 miles",
      setupTime: "45-60 minutes",
      pickupTime: "Next day pickup available",
    },
  },
  {
    id: "elegant-evening",
    name: "Elegant Evening Package",
    description: "Sophisticated setup for upscale events",
    image: "/modern-black-mobile-bar-cart-gold-accents-luxury-e.jpg",
    originalPrice: 599,
    packagePrice: 499,
    savings: 100,
    items: ["Modern Noir Cart", "Market Umbrella (Navy)", "Premium Cooler", "Serving Trays (Gold)", "LED Lights"],
    popular: false,
    fullDescription:
      "Create an unforgettable upscale experience with our Elegant Evening Package. The sophisticated Modern Noir cart paired with a classic navy market umbrella, premium cooler, elegant gold serving trays, and atmospheric LED lighting sets the perfect tone for refined celebrations and corporate events.",
    specifications: [
      "Modern Noir cart with matte black finish and gold hardware",
      "9ft Market Umbrella in Navy with hardwood pole",
      "Premium 50-quart stainless steel cooler with ice",
      "3-piece Gold Serving Tray Set (Small, Medium, Large)",
      "LED String Lights with timer function",
    ],
    idealFor: ["Corporate Galas", "Anniversary Parties", "Upscale Weddings", "Evening Receptions"],
    rentalDetails: {
      minimumRental: "4 hours",
      deliveryIncluded: "Within 20 miles",
      setupTime: "45-60 minutes",
      pickupTime: "White glove pickup service",
    },
  },
  {
    id: "wedding-romance",
    name: "Wedding Romance Package",
    description: "Perfect for your special day",
    image: "/vintage-pink-mobile-bar-cart-floral-decorations-ro.jpg",
    originalPrice: 569,
    packagePrice: 469,
    savings: 100,
    items: [
      "Vintage Romance Cart",
      "Market Umbrella (White)",
      "Custom Signage",
      "Glassware Set",
      "Fringe Decor (Rose Gold)",
    ],
    popular: false,
    fullDescription:
      "Make your wedding day even more magical with our Wedding Romance Package. The beautiful Vintage Romance cart with its soft blush finish, elegant white market umbrella, personalized signage, and romantic rose gold fringe creates the perfect backdrop for your celebration of love.",
    specifications: [
      "Vintage Romance cart in distressed blush pink",
      "9ft White Market Umbrella with premium fabric",
      "Custom Acrylic or Wood Signage (12x18 with design consultation)",
      "50-piece Premium Glassware Set",
      "10ft Rose Gold Metallic Fringe Decorations",
    ],
    idealFor: ["Weddings", "Bridal Showers", "Engagement Parties", "Romantic Celebrations"],
    rentalDetails: {
      minimumRental: "6 hours",
      deliveryIncluded: "Within 20 miles",
      setupTime: "60 minutes with styling",
      pickupTime: "Flexible next-day pickup",
    },
  },
]
